[project]
name = "mcstatus-api"
version = "0.1.0"
description = "A Minecraft Server status API based on FastAPI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "uvicorn>=0.30.0",
    "mcstatus>=12.0.5",
]
